export enum DirectoryErrorType {
  MISSING_HANDLER = 'MISSING_HANDLER',
  INVALID_DIRECTORY_NAME = 'INVALID_DIRECTORY_NAME',
  INVALID_PARAMETER_NAME = 'INVALID_PARAMETER_NAME',
  NOT_A_DIRECTORY = 'NOT_A_DIRECTORY',
  EMPTY_API_FOLDER = 'EMPTY_API_FOLDER',
}
